Cottontaildb adapter
polypheny/Polypheny-DB pull request #271
Opened 2021-01-12 12:55 UTC by schoenja

2021-01-18 15:13 UTC, vogti requested changes
Thx @schoenja for this PR. Could you please have a look at my questions? Furthermore, it would be very nice if you would find the time to scroll through your changes and remove outdated todos and remove out-commented code which is of no further use (please do not remove code which might be useful in future).

2021-01-18 15:13 UTC, vogti commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/rel/CottontailValues.java
> +    }
Is this code still used?

2021-01-26 09:17 UTC, schoenja commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/rules/CottontailRules.java
> +//                new CottontailSortRule( out, relBuilderFactory ),
Pure sorting is not supported by Cottontail-DB. The rule has been replaced by the `CottontailSortAndProjectRule`.

2021-01-26 09:22 UTC, schoenja commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/CottontailWrapper.java
> +    }
This method originates from the original Wrapper in the Cineast project. I currently can't say whether Cottontail-DB indices and Polypheny-DB indices are compatible.

2021-01-26 09:23 UTC, schoenja commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/rel/CottontailValues.java
> +    }
Nope, will be deleted.

2021-01-30 15:27 UTC, schoenja commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/rel/CottontailLimit.java
> +//            context.limit = RexLiteral.intValue( fetch );
No, the entire `CottontailLimit` class is no longer required, as those limits are combined with `CottontailSortAndProject`.

2021-01-30 16:00 UTC, schoenja commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/CottontailStore.java
> +        } );
Yes, it is currently unfinished. Do you want me to just delete it or keep it?

2021-01-30 16:14 UTC, vogti commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/CottontailStore.java
> +        } );
Please add a comment on top of the method and keep the code.

2021-01-30 16:21 UTC, vogti commented on cottontail-adapter/src/main/java/org/polypheny/db/adapter/cottontail/CottontailWrapper.java
> +    }
The implementation for managing store level indexes is very generic. There should be no compatibility issues. Adding support for store level indexes only requires implementing the methods in the store interface. I can do that, but I need a _dropIndex_ method and a short example on how to use these methods.

2021-03-12 13:15 UTC, vogti approved these changes
Thx @schoenja for this PR!

2021-03-12 14:18 UTC, merged